### ISSUE TITLE
接口错误 - {}

### ISSUE THREAD

**Issue by AjianNie** [solywsh/bob-relingo#4]
Bob 1.10.0 [182]
relingo 插件最新版本
1. 点击验证-> 输入验证码 -> 接口错误 - {}
2. 插件的窗口翻译界面显示: "Cannot read properties of null (reading 'config')"

**Comment by solywsh** [comment]
这个问题应该也和#2有关，请先更新插件再重新尝试。

不过在获取验证码时流程应该是这样
1.输入邮箱，点击保存。这时插件才能从bob获取邮箱信息
2.点击最下角的验证。插件会检测验证码和token状态，如果没有会向Reingo请求验证码，并提示。
3.收到验证码后填入验证码，然后点击保存，再次点击验证。

所以请注意填值之后都需要先点击保存，再点击验证，不然插件无法获取到您填入的信息。
