### ISSUE TITLE
发音好像不对 resume

### ISSUE THREAD

**Issue by selaselah** [solywsh/bob-relingo#5]
翻译的床口里，有两行发音
```
resume
美 [/ri'zu:m/] 🗣️ 
英 [/ri'zju:m/] 🗣️ 
```

无论点击哪个，发音都是默认美音（这个美音可能和我relingo默认发美音有关）

**Comment by solywsh** [comment]
你好，为了减轻relingo的服务器压力， 发音tts是使用的有道翻译的接口，并且当时在写接口时只使用了有道翻译的美式发音接口，等我周末的时候改一下。
https://github.com/solywsh/bob-relingo/blob/a8bb3d3d0511b6d68682edd22e35822ea773abda/src/word.js#L43
[https://opengraph.githubassets.com/1bb29040e3e93484eb0b32e8634614aada4c18c44116b80bf219e362ac76099b/solywsh/bob-relingo]<https://github.com/solywsh/bob-relingo/blob/a8bb3d3d0511b6d68682edd22e35822ea773abda/src/word.js#L43>
bob-relingo/src/word.js at a8bb3d3d0511b6d68682edd22e35822ea773abda · solywsh/bob-relingo<https://github.com/solywsh/bob-relingo/blob/a8bb3d3d0511b6d68682edd22e35822ea773abda/src/word.js#L43>
bob的relingo联动，可显示relingo个人单词掌握情况. Contribute to solywsh/bob-relingo development by creating an account on GitHub.
github.com


________________________________
发件人: Chen ***@***.***>
发送时间: 2024年8月1日 8:39
收件人: solywsh/bob-relingo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [solywsh/bob-relingo] 发音好像不对 resume (Issue #5)


翻译的床口里，有两行发音

resume
美 [/ri'zu:m/] 🗣️
英 [/ri'zju:m/] 🗣️


无论点击哪个，发音都是默认美音（这个美音可能和我relingo默认发美音有关）
